# Generated by Django 5.2.9 on 2025-12-13 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-enrollment_date', '-id'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
    ]
